# إعدادات البوت الآمنة
bot_token: '7965653302:AAHz9E1veaDgMVOg-0sJmtVe4Tdc9kXg_Io' # ❗ غيّر هذا التوكن
staffchat_id: '-1002322245160'
owner_id: '5247871063'
spam_time: 300000
spam_cant_msg: 5

parse_mode: 'Markdown'

# إعدادات التذاكر
allow_private: false
direct_reply: false
auto_close_tickets: true
anonymous_tickets: true
anonymous_replies: true
show_auto_replied: false
show_user_ticket: false
autoreply_confirmation: true
clean_replies: false
pass_start: false

web_server: false
web_server_port: 8080

dev_mode: true

# اللغة العربية المعدلة
language:
  startCommandText: 'مرحبًا بكم في الدعم الفني! كيف يمكننا مساعدتك؟'
  faqCommandText: 'الأسئلة الشائعة'
  helpCommandText: "الأوامر المتاحة: /help /id"
  helpCommandStaffText: |
    أوامر الدعم:
    /open - عرض التذاكر
    /close - إغلاق التذكرة
    /ban - حظر مستخدم
    /unban - إلغاء الحظر
  confirmationMessage: "تم استلام طلبك، سيتم الرد قريبًا"
  blockedSpam: 'تم تجاوز الحد المسموح من الرسائل'
  ticket: 'تذكرة'
  closed: 'مغلقة'
  dear: 'مرحبًا'
  regards: 'مع التقدير،'
  msg_sent: 'تم الإرسال بنجاح'
  services: 'اختر الخدمة المطلوبة'
  customer: 'عميل'
  back: 'رجوع'
  openTickets: 'التذاكر النشطة'
  support: 'الدعم الفني'
  ticketClosed: 'تم إنهاء التذكرة بنجاح'

# الردود التلقائية المعدلة
autoreply:
  question: 'حالة الطلب'
  answer: 'سيتم تحديث حالة طلبك خلال ٢٤ ساعة'

# التصنيفات المعدلة
categories:
- name: "المساعدة الفنية"
  subgroups:
    - name: "أعطال البرامج"
      group_id: "-1002298654090"
    - name: "مشاكل الشبكة"
      group_id: "-1002298654090"

- name: "الشكاوى"
  subgroups:
    - name: "شكاوى مالية"
      group_id: "-1002298654090"
    - name: "شكاوى فنية"
      group_id: "-1002298654090"

- name: "استفسارات عامة"
  group_id: "-1002298654090"